import '../onboarding_screen_one_screen/widgets/learningframe_item_widget.dart';import 'controller/onboarding_screen_one_controller.dart';import 'models/learningframe_item_model.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:flutter_elearning_app/core/app_export.dart';import 'package:flutter_elearning_app/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class OnboardingScreenOneScreen extends GetWidget<OnboardingScreenOneController> {const OnboardingScreenOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 24.v), child: Column(children: [SizedBox(height: 476.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgObjectBlack900, height: 421.v, width: 428.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgRectangle4487476x396, height: 476.v, width: 396.h, alignment: Alignment.center)])), SizedBox(height: 33.v), _buildLearningFrame(), SizedBox(height: 29.v), Obx(() => SizedBox(height: 7.v, child: AnimatedSmoothIndicator(activeIndex: controller.sliderIndex.value, count: controller.onboardingScreenOneModelObj.value.learningframeItemList.value.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 6, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primary.withOpacity(0.46), dotHeight: 7.v, dotWidth: 7.h)))), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.symmetric(horizontal: 16.h), onPressed: () {onTapNext();}), SizedBox(height: 19.v), GestureDetector(onTap: () {onTapTxtSkip();}, child: Text("lbl_skip".tr, style: theme.textTheme.bodyLarge)), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildLearningFrame() { return Padding(padding: EdgeInsets.only(left: 17.h, right: 22.h), child: Obx(() => CarouselSlider.builder(options: CarouselOptions(height: 140.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {controller.sliderIndex.value = index;}), itemCount: controller.onboardingScreenOneModelObj.value.learningframeItemList.value.length, itemBuilder: (context, index, realIndex) {LearningframeItemModel model = controller.onboardingScreenOneModelObj.value.learningframeItemList.value[index]; return LearningframeItemWidget(model);}))); } 
/// Navigates to the onboarding1Screen when the action is triggered.
onTapNext() { Get.toNamed(AppRoutes.onboarding1Screen, ); } 
/// Navigates to the onboarding1Screen when the action is triggered.
onTapTxtSkip() { Get.toNamed(AppRoutes.onboarding1Screen, ); } 
 }
